### ISSUE TITLE
Might be a dumb question

### ISSUE THREAD

**Issue by CodyWHageman** [ndrabins/react-redux-firebase-material-electron-starter#2]
Hi, 
So I'm using this and it's working lovely. I haven't been able to get an app I was working on to work with firebase due to a gRPC error. So anyways works great now after using you starter code here. This is probably a dumb question but how do I get it to stop opening the web browser page of react. I just need it to run electron. I've tried all sorts of different things and can't seem to get it.

**Comment by ndrabins** [comment]
hey Caarn! Not a dumb question at all. 

So I currently have it set up so "npm start" will open both the web dev server and electron server. 

If you want to just develop electron you can use "npm electron-start" and it will only open up electron. 

Also sorry I haven't kept this repo up to date but you will definitely want to update your material-ui and firebase packages! 

I will try to get around to updating this repo this week.
